# Generated by Django 5.1.2 on 2024-10-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('predicted_price', models.FloatField()),
                ('day', models.IntegerField()),
                ('date_predicted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
